# Generated by Django 4.2.4 on 2023-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("actual_price", models.FloatField(max_length=10)),
                ("selling_price", models.FloatField(max_length=10, null=True)),
                ("average_rating", models.FloatField(max_length=5)),
                ("total_ratings", models.IntegerField(max_length=50000,default=0,null=True)),
                ("category", models.CharField(max_length=40)),
                ("img_path", models.CharField(max_length=64)),
                ("subcategory", models.CharField(max_length=30, null=True)),
                (
                    "poster",
                    models.CharField(
                        default="https://www.flipkart.com", max_length=160
                    ),
                ),
                ("discount", models.IntegerField(default=0)),
                ("brought", models.BooleanField(default=False, null=True)),
                ("description", models.TextField(max_length=200)),
                ("details", models.CharField(max_length=150, null=True)),
                ("recommended", models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
