# Generated by Django 4.2.4 on 2023-08-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductRecommender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="total_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
