# Generated by Django 4.2.4 on 2023-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductRecommender", "0002_alter_product_total_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(default="https://www.flipkart.com/"),
        ),
    ]
