# Generated by Django 4.2.4 on 2023-10-03 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProductRecommender", "0004_alter_product_brought"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brought",
        ),
        migrations.AddField(
            model_name="product",
            name="brought",
            field=models.ManyToManyField(
                related_name="bought_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
