# Generated by Django 4.2.4 on 2023-10-03 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProductRecommender", "0008_product_liked_product_viewed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="recommended",
        ),
        migrations.AddField(
            model_name="product",
            name="recommended",
            field=models.ManyToManyField(
                related_name="recommended", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
